### ISSUE TITLE
Field Icon and Clicking

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_Windows#21]
The field icon on the far right, does not appear to activate the dialog for picking account.   Only by putting focus in the field, will I see the pop-up dialog.   Can we make the icon clickable?

**Comment by IrynaPovkh** [comment]
fixed

**Comment by bravozulu1** [comment]
Issue moved to [BluStor/PasswordVault_IE_Plugin #5](https://github.com/BluStor/PasswordVault_IE_Plugin/issues/5) via [**ZenHub**](https://www.zenhub.com/)
