### ISSUE TITLE
Multiple Login Attempts

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_Windows#22]
i'm seeing multiple login attempts when accessing Staples with invalid user and password.  The plug-in tried to log me in three times.  But my password was expired or account deactivated.

The plug-in should only attempt to login one time and if it fails the user can take additional action.

1.  Open the following URL
https://www.staples.com/
2.  Click sign in button in the middle of the page
3.  My plugin tried to login three times with BAD password.

**Comment by IrynaPovkh** [comment]
fixed

**Comment by bravozulu1** [comment]
Issue moved to [BluStor/PasswordVault_IE_Plugin #4](https://github.com/BluStor/PasswordVault_IE_Plugin/issues/4) via [**ZenHub**](https://www.zenhub.com/)
