### ISSUE TITLE
Just Giving Not Auto Filling

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_Windows#23]
Dashlane works.  This website is not auto filling in user and password.  I did authorize the access to the account.

https://www.justgiving.com

**Comment by IrynaPovkh** [comment]
fixed

**Comment by bravozulu1** [comment]
Issue moved to [BluStor/PasswordVault_IE_Plugin #1](https://github.com/BluStor/PasswordVault_IE_Plugin/issues/1) via [**ZenHub**](https://www.zenhub.com/)
