### ISSUE TITLE
Gmail Auto Fill Password Field

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_Windows#24]
Logging into gmail the password field was not auto populated.   See screen shot.

![image](https://user-images.githubusercontent.com/10087224/28039566-72289760-6588-11e7-8c5e-969a45968d6e.png)

**Comment by IrynaPovkh** [comment]
it works on our computer, are you sure that KeePass had the relevant credentials for google?

**Comment by bravozulu1** [comment]
Issue moved to [BluStor/PasswordVault_IE_Plugin #3](https://github.com/BluStor/PasswordVault_IE_Plugin/issues/3) via [**ZenHub**](https://www.zenhub.com/)
