### ISSUE TITLE
REI Auto Login Fails

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_Windows#25]
Auto login to REI seems to hang and only display the large blue dialog.   See screen shot.

http://www.rei.com

![image](https://user-images.githubusercontent.com/10087224/28039733-fb624eb8-6588-11e7-8d49-a8d948fbbc81.png)

**Comment by IrynaPovkh** [comment]
this is not a bug. Please, click on dismiss button, after that click on "Sign in". You will see that form is filled. Plugin is trying to autologin with wrong credentials. That is why you see this screen

**Comment by bravozulu1** [comment]
Issue moved to [BluStor/PasswordVault_IE_Plugin #2](https://github.com/BluStor/PasswordVault_IE_Plugin/issues/2) via [**ZenHub**](https://www.zenhub.com/)
